name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Staticcheck Install
      run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
    - name: Staticcheck Test
      run: staticcheck ./...
      
    - name: Vet Test
      run: go vet -v ./...
      
    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic -tags test ./...
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0    

    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      id: Depcheck
      with:
        project: 'util'
        path: './...'
        format: 'HTML'    
        args: >
          --failOnCVSS 0
          --enableRetired

    - name: Upload Dependency Check Test results
      uses: actions/upload-artifact@master
      with:
        name: Depcheck report
        path: ${{github.workspace}}/reports
